# Generated by Django 3.0.5 on 2020-04-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Chat', verbose_name='Chat')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='contact.Contact', verbose_name='Contacto')),
            ],
        ),
    ]
