# Generated by Django 3.0.5 on 2020-04-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200419_1626'),
        ('contact', '0002_auto_20200419_1626'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='chat.Chat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='contact.Contact', verbose_name='Contacto'),
        ),
    ]
