# Generated by Django 3.0.5 on 2020-04-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typechat', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('participants', models.ManyToManyField(blank=True, related_name='chat', to='contact.Contact', verbose_name='Participantes')),
                ('type_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typechat.TypeChat', verbose_name='Tipo Chat')),
            ],
        ),
    ]
