# Generated by Django 3.0.5 on 2020-04-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typechat', '0001_initial'),
        ('chat', '0002_chat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='typechat.TypeChat', verbose_name='Tipo Chat'),
        ),
    ]
